site_name: TeaNotes
theme:
  name: material
  logo: img/teapot.png
  favicon: img/teapot.png
  language: en
  custom_dir: overrides
  palette:
    primary: white
    scheme: default
nav:
  - Blog:
      - blog/index.md
  - Tree Map: treechart.md
plugins:
  - blog:
      post_readtime_words_per_minute: 200
      pagination_per_page: 4
extra_css:
  - css/frame.css
  - javascript/photoswipe/dist/photoswipe.css
markdown_extensions:
  - md_extensions.rating_extension:RatingExtension
  - md_extensions.gallery_extension:GalleryExtension
  - md_extensions.treechart_extension:TreeChartExtension
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - toc:
     toc_depth: 0
     permalink: false
extra:
  generator: false
  analytics:
    provider: google
    property: G-591BE4WH3V


